name: nubank_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  provider: ^5.0.0
  mdi: ^5.0.0-nullsafety.0
  page_transition: ^2.0.2
  bootstrap_icons: ^1.5.0
  flutter_masked_text2: ^0.9.1
  easy_localization: ^3.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family:  NuIcons
      fonts:
        - asset: assets/fonts/NuIcons.ttf

    - family: Gotham-SSm
      fonts:
        - asset: assets/fonts/Gotham-SSm/GothamSSm-XLight.ttf
          weight: 200
        - asset: assets/fonts/Gotham-SSm/GothamSSm-XLightItalic.ttf
          weight: 200
          style: italic
          
        - asset: assets/fonts/Gotham-SSm/GothamSSm-Light.ttf
          weight: 300
        - asset: assets/fonts/Gotham-SSm/GothamSSm-LightItalic.ttf
          weight: 300
          style: italic
          
        - asset: assets/fonts/Gotham-SSm/GothamSSm-Book.ttf
          weight: 400
        - asset: assets/fonts/Gotham-SSm/GothamSSm-BookItalic.ttf
          weight: 400
          style: italic
          
        - asset: assets/fonts/Gotham-SSm/GothamSSm-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gotham-SSm/GothamSSm-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Gotham-SSm/GothamSSm-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gotham-SSm/GothamSSm-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Gotham-SSm/GothamSSm-Black.ttf
          weight: 900
        - asset: assets/fonts/Gotham-SSm/GothamSSm-BlackItalic.ttf
          weight: 900